//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModels : DbContext
    {
        public DbModels()
            : base("name=DbModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<certifikat> certifikats { get; set; }
        public DbSet<certifikat_osoblje> certifikat_osoblje { get; set; }
        public DbSet<evidencija_oprema> evidencija_oprema { get; set; }
        public DbSet<evidencija_osoblje> evidencija_osoblje { get; set; }
        public DbSet<natjecaj> natjecajs { get; set; }
        public DbSet<natjecaj_ponuda> natjecaj_ponuda { get; set; }
        public DbSet<natjecaj_transakcija_oprema> natjecaj_transakcija_oprema { get; set; }
        public DbSet<natjecaj_transakcija_osoblje> natjecaj_transakcija_osoblje { get; set; }
        public DbSet<normativ_oprema> normativ_oprema { get; set; }
        public DbSet<normativ_osoblje> normativ_osoblje { get; set; }
        public DbSet<oprema> opremas { get; set; }
        public DbSet<osoblje> osobljes { get; set; }
        public DbSet<osoblje_zanimanje> osoblje_zanimanje { get; set; }
        public DbSet<posao> posaos { get; set; }
        public DbSet<posao_transakcija_oprema> posao_transakcija_oprema { get; set; }
        public DbSet<posao_transakcija_osoblje> posao_transakcija_osoblje { get; set; }
        public DbSet<posao_usluga> posao_usluga { get; set; }
        public DbSet<skladiste> skladistes { get; set; }
        public DbSet<skladiste_opreme> skladiste_opreme { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<transakcija_oprema> transakcija_oprema { get; set; }
        public DbSet<transakcija_osoblje> transakcija_osoblje { get; set; }
        public DbSet<unajmljena_oprema> unajmljena_oprema { get; set; }
        public DbSet<usluga> uslugas { get; set; }
        public DbSet<usluga_kategorija> usluga_kategorija { get; set; }
        public DbSet<zanimanje> zanimanjes { get; set; }
    }
}
