//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class natjecaj
    {
        public natjecaj()
        {
            this.natjecaj_ponuda = new HashSet<natjecaj_ponuda>();
            this.natjecaj_transakcija_osoblje = new HashSet<natjecaj_transakcija_osoblje>();
            this.natjecaj_transakcija_oprema = new HashSet<natjecaj_transakcija_oprema>();
        }
    
        public int id { get; set; }
        public string raspisala_osoba { get; set; }
        public string opis { get; set; }
        public decimal iznos { get; set; }
        public System.DateTime datum_od { get; set; }
        public System.DateTime datum_do { get; set; }
        public string pobjednik { get; set; }
        public decimal prihvacen_iznos { get; set; }
    
        public virtual ICollection<natjecaj_ponuda> natjecaj_ponuda { get; set; }
        public virtual ICollection<natjecaj_transakcija_osoblje> natjecaj_transakcija_osoblje { get; set; }
        public virtual ICollection<natjecaj_transakcija_oprema> natjecaj_transakcija_oprema { get; set; }
    }
}
