//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oprema
    {
        public oprema()
        {
            this.evidencija_oprema = new HashSet<evidencija_oprema>();
            this.normativ_oprema = new HashSet<normativ_oprema>();
            this.oprema1 = new HashSet<oprema>();
            this.skladiste_opreme = new HashSet<skladiste_opreme>();
            this.transakcija_oprema = new HashSet<transakcija_oprema>();
            this.unajmljena_oprema = new HashSet<unajmljena_oprema>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string inventarni_broj { get; set; }
        public decimal kupljena_vrijednost { get; set; }
        public decimal knjigovodstvena_vrijednost { get; set; }
        public string tip { get; set; }
        public string dostupna { get; set; }
        public decimal broj_radnih_sati { get; set; }
        public Nullable<int> referentni_tip { get; set; }
    
        public virtual ICollection<evidencija_oprema> evidencija_oprema { get; set; }
        public virtual ICollection<normativ_oprema> normativ_oprema { get; set; }
        public virtual ICollection<oprema> oprema1 { get; set; }
        public virtual oprema oprema2 { get; set; }
        public virtual ICollection<skladiste_opreme> skladiste_opreme { get; set; }
        public virtual ICollection<transakcija_oprema> transakcija_oprema { get; set; }
        public virtual ICollection<unajmljena_oprema> unajmljena_oprema { get; set; }
    }
}
