//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osoblje
    {
        public osoblje()
        {
            this.certifikat_osoblje = new HashSet<certifikat_osoblje>();
            this.evidencija_osoblje = new HashSet<evidencija_osoblje>();
            this.normativ_osoblje = new HashSet<normativ_osoblje>();
            this.osoblje_zanimanje = new HashSet<osoblje_zanimanje>();
            this.transakcija_osoblje = new HashSet<transakcija_osoblje>();
        }
    
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datum_rodjenja { get; set; }
        public string zauzet { get; set; }
    
        public virtual ICollection<certifikat_osoblje> certifikat_osoblje { get; set; }
        public virtual ICollection<evidencija_osoblje> evidencija_osoblje { get; set; }
        public virtual ICollection<normativ_osoblje> normativ_osoblje { get; set; }
        public virtual ICollection<osoblje_zanimanje> osoblje_zanimanje { get; set; }
        public virtual ICollection<transakcija_osoblje> transakcija_osoblje { get; set; }
    }
}
