//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posao_usluga
    {
        public int id { get; set; }
        public int posao_id { get; set; }
        public int usluga_id { get; set; }
    
        public virtual posao posao { get; set; }
        public virtual usluga usluga { get; set; }
    }
}
