//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posao
    {
        public posao()
        {
            this.evidencija_oprema = new HashSet<evidencija_oprema>();
            this.evidencija_osoblje = new HashSet<evidencija_osoblje>();
            this.posao_transakcija_osoblje = new HashSet<posao_transakcija_osoblje>();
            this.posao_transakcija_oprema = new HashSet<posao_transakcija_oprema>();
            this.posao_usluga = new HashSet<posao_usluga>();
        }
    
        public int id { get; set; }
        public string grad { get; set; }
        public string lokacija { get; set; }
        public string sklopljen { get; set; }
        public string zavrsen { get; set; }
        public System.DateTime trajanje_od { get; set; }
        public System.DateTime trajanje_do { get; set; }
    
        public virtual ICollection<evidencija_oprema> evidencija_oprema { get; set; }
        public virtual ICollection<evidencija_osoblje> evidencija_osoblje { get; set; }
        public virtual ICollection<posao_transakcija_osoblje> posao_transakcija_osoblje { get; set; }
        public virtual ICollection<posao_transakcija_oprema> posao_transakcija_oprema { get; set; }
        public virtual ICollection<posao_usluga> posao_usluga { get; set; }
    }
}
