//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skladiste_opreme
    {
        public int id { get; set; }
        public int skladiste_id { get; set; }
        public int oprema_id { get; set; }
        public int broj_na_polici { get; set; }
        public int polica { get; set; }
        public int stalak { get; set; }
    
        public virtual oprema oprema { get; set; }
        public virtual skladiste skladiste { get; set; }
    }
}
