//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transakcija_oprema
    {
        public transakcija_oprema()
        {
            this.natjecaj_transakcija_oprema = new HashSet<natjecaj_transakcija_oprema>();
            this.posao_transakcija_oprema = new HashSet<posao_transakcija_oprema>();
        }
    
        public int id { get; set; }
        public System.DateTime datum { get; set; }
        public decimal prihod { get; set; }
        public decimal trosak { get; set; }
        public int oprema_id { get; set; }
    
        public virtual ICollection<natjecaj_transakcija_oprema> natjecaj_transakcija_oprema { get; set; }
        public virtual oprema oprema { get; set; }
        public virtual ICollection<posao_transakcija_oprema> posao_transakcija_oprema { get; set; }
    }
}
