//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unajmljena_oprema
    {
        public int id { get; set; }
        public System.DateTime koristenje_od { get; set; }
        public System.DateTime koristenje_do { get; set; }
        public string tip { get; set; }
        public string osoba { get; set; }
        public int oprema_id { get; set; }
    
        public virtual oprema oprema { get; set; }
    }
}
