//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usluga_kategorija
    {
        public usluga_kategorija()
        {
            this.uslugas = new HashSet<usluga>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<usluga> uslugas { get; set; }
    }
}
