//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usluga
    {
        public usluga()
        {
            this.normativ_oprema = new HashSet<normativ_oprema>();
            this.normativ_osoblje = new HashSet<normativ_osoblje>();
            this.posao_usluga = new HashSet<posao_usluga>();
        }
    
        public int id { get; set; }
        public int tip { get; set; }
        public double cijena { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<normativ_oprema> normativ_oprema { get; set; }
        public virtual ICollection<normativ_osoblje> normativ_osoblje { get; set; }
        public virtual ICollection<posao_usluga> posao_usluga { get; set; }
        public virtual usluga_kategorija usluga_kategorija { get; set; }
    }
}
