//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace organiziranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zanimanje
    {
        public zanimanje()
        {
            this.osoblje_zanimanje = new HashSet<osoblje_zanimanje>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<osoblje_zanimanje> osoblje_zanimanje { get; set; }
    }
}
